const recommendedDB = [
  {
    id: 1,
    img: "/images/cardIMG/movie1.jpg",
    title: "The Undead",
    pref: "Recommended",
    category: "Romantic",
  },
  {
    id: 2,
    img: "/images/cardIMG/movie2.jpg",
    title: "GAME WEB",
    pref: "Recommended",
    category: "Action",
  },
  {
    id: 3,
    img: "/images/cardIMG/movie3.jpg",
    title: "BATMAN",
    pref: "Recommended",
    category: "Scifi",
  },
  {
    id: 4,
    img: "/images/cardIMG/movie4.jpg",
    title: "STAR WARS",
    pref: "Recommended",
    category: "Romantic",
  },
  {
    id: 5,
    img: "/images/cardIMG/movie5.jpg",
    title: "RETURNS",
    pref: "Recommended",
    category: "Action",
  },
  {
    id: 6,
    img: "/images/cardIMG/movie6.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Romantic",
  },
  {
    id: 7,
    img: "/images/cardIMG/movie7.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Scifi",
  },
  {
    id: 8,
    img: "/images/cardIMG/movie8.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Action",
  },
  {
    id: 9,
    img: "/images/cardIMG/movie9.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Romantic",
  },
  {
    id: 10,
    img: "/images/cardIMG/movie10.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Scifi",
  },
  {
    id: 11,
    img: "/images/cardIMG/movie11.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Action",
  },
  {
    id: 12,
    img: "/images/cardIMG/movie12.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Romantic",
  },
  {
    id: 13,
    img: "/images/cardIMG/movie13.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Scifi",
  },
  {
    id: 14,
    img: "/images/cardIMG/movie14.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Action",
  },
  {
    id: 15,
    img: "/images/cardIMG/movie15.jpg",
    title: "I AM LISA",
    pref: "Recommended",
    category: "Romantic",
  },
];
export default recommendedDB;
