const recommendedDB = [
  {
    id: 1,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211864/jayflix%20vid%20posters/photo_2022-09-02_18-44-34_s1ebhk.jpg",

    title: "SMALL TALKS",
    pref: "Recommended",
    category: "Romantic",
    description:
      "A once happy and perfect marriage is at the brink of crashing after several rounds of presumed infidelity accusations. There appears to be a subtle enemy from within",
    cast: "Bimbo Ademoye, Eddie Watson, Bolaji ",
    director: "Stanley Obi",
    download:
      "https://drive.google.com/file/d/1XHgkc3wq0nFBPikTAwCv1vvnhz0VOt5P/view?usp=sharing",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211773/jayflix%20vid%20posters/photo_2022-09-02_18-46-15_apgmgr.jpg",
    title: "TEMI’S DIARY ",
    pref: "Recommended",
    category: "Action",
    description:
      "When Temi relocates to the village with the family after her father’s death, she finds herself in constant battle with her envious, abusive step-mother and her selfish step-sisters.",
    cast: " Lota Chukwu, Stan Nze, Jide Kosoko, Tessy Brown, Genoveva Ume ",
    director: "",
    download:
      "https://drive.google.com/file/d/1GWQcLuhYvstSxfA9ItqiRHxMLcHtYfcg/view?usp=sharing",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211789/jayflix%20vid%20posters/photo_2022-09-02_18-56-33_f7afai.jpg",
    title: "THE BIG MISTAKE ",
    pref: "Recommended",
    category: "Scifi",
    description:
      "A player, who can’t seem to settle down with one girl gets emotionally attached to his sisters boss.",
    cast: " Kunle Remi , Ruth Kadiri , Bofie Ito’mbra , Darlene Odogbili , Eddy Egbo ",
    director: "",
    download:
      "https://drive.google.com/file/d/10UtwLZgNyiFXuzO2TF9oSyy_mct_X16S/view?usp=sharing",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211774/jayflix%20vid%20posters/photo_2022-09-02_18-47-47_x8c9qr.jpg",
    title: "THE GHOST AND THE HOUSE OF TRUTH",
    pref: "Recommended",
    category: "Romantic",
    description:
      "Bola Ogun is a dedicated counselor, who facilitates reconciliation sessions between convicts and the victims of their crimes. When her own daughter goes missing, her belief in forgiveness is tested. ",
    cast: " Kate Henshaw, Keira HeWatch, Fabian Adeoye Lojede, Kate Henshaw-Nuttal, Susan Wokoma, Oludara Egerton Shygnle, Kemi Lala Akindoju ",
    director: "",
    download:
      "https://drive.google.com/file/d/1M4omTzb2JijUrGFmMBREqWI48rO7KIe0/view?usp=sharing",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211846/jayflix%20vid%20posters/photo_2022-09-02_18-41-58_vfcwji.jpg",
    title: "THE HOOKUP",
    pref: "Recommended",
    category: "Action",
    description:
      "Deeply in love and in poverty, a couple’s loyalty is tested by an egotistic cynic",
    cast: " Kate Henshaw, Keira HeWatch, Fabian Adeoye Lojede, Kate Henshaw-Nuttal, Susan Wokoma, Oludara Egerton Shygnle, Kemi Lala Akindoju ",
    director: "",
    download:
      "https://drive.google.com/file/d/1wAvAAYTKrwzNsDiYoiXoTWP-831BzzMD/view?usp=sharing",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211856/jayflix%20vid%20posters/photo_2022-09-02_18-43-44_pqbw31.jpg",
    title: "THE PENDULUM",
    pref: "Recommended",
    category: "Romantic",
    description:
      "The romantic story of a player whose cahrm fails as he meets his dream girl ",
    cast: " Duncan, Makanaki, Keira HeWatch, Fabian Adeoye Lojede, Kate Henshaw-Nuttal, Susan Wokoma, ",
    director: "",
    download:
      "https://drive.google.com/file/d/1pmW1QwZFItYhHAf5tcneUA7fpJ1_VQ97/view?usp=sharing",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211847/jayflix%20vid%20posters/photo_2022-09-02_18-42-33_wjixzi.jpg",
    title: "THE REAL US",
    pref: "Recommended",
    category: "Romantic",
    description:
      "Through the help of his female bestie, Nnamdi rises up to stardom from a common gateman. He must now choose between friendship and his newfound fame.",
    cast: "  Alexx Ekubo, Bimbo Ademoye, Timini Egbuson, Emem Ufot, Audrey Harrison, Kemi Ikuseeden, Adebayo Davies, Chinonso Arubayi, Ivy Antiev, Maria Thomas, Emeka Darlynton, Toyosi Benjamin, Ifeoluwa Eninla, Ayah Favour, Rachel Edward, Samuel Abah",
    director: "",
    download:
      "https://drive.google.com/file/d/1WWto5Daaa-8VGhTccMge4E0Nw0v7bCnT/view?usp=sharing",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211830/jayflix%20vid%20posters/photo_2022-09-02_18-35-00_teywo2.jpg",
    title: " UP NORTH",
    pref: "Recommended",
    category: "Romantic",
    description:
      "Up North”  A film about Bassey Otuekong, who gets sent to Bauchi for his NYSC assignment as a punishment for defying his father.",
    cast: "  Banky W, Rahama Sadau, T. Boss, Ibrahim Suleiman, Kanayo O. Kanayo, Adesua Etomi, Michelle Dede",
    director: "",
    download:
      "https://drive.google.com/file/d/1sMBE0X2m58mh0RHj8em2vAALeRDEU20C/view?usp=sharing",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211809/jayflix%20vid%20posters/photo_2022-09-02_18-19-39_z14pfl.jpg",
    title: "WEDDING PARTY 2",
    pref: "Recommended",
    category: "Romantic",
    description:
      "The Wedding Party 2: Destination Dubai Nonso continues his romance with Deirdre, the bridesmaid from London. While on a dinner date, Nonso proposes to Deirdre by accident and sets off a chain of events too powerful to stop. Deirdre’s upper-crust British family are against the match, as are some members of the Nigerian clan, but Deirdre’s.",
    cast: "  Adesua Etomi, Banky Wellington, Richard Mofe-Damijo, Ireti Doyle, Ali-Baba, Daniella Down, Omoni Oboli, Enyinna Nwigwe",
    director: "",
    download:
      "https://drive.google.com/file/d/1K3giaR0Bwu6QxXh91ObCslWL5axfNCo4/view?usp=sharing",
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211836/jayflix%20vid%20posters/photo_2022-09-02_18-37-07_m5j4zb.jpg",
    title: "ZERO HOUR",
    pref: "Recommended",
    category: "Romantic",
    description:
      "After his father passes, the heir to a retail empire returns to take over the family business but faces a controversy involving laundering and murder.",
    cast: " Richard Mofe-Damijo, Alex Ekubo, Ali Nuhu, Eucharia Anunobi, Rahama Sadau, Ene Oloja, Halima Yusuf",
    director: "",
    download:
      "https://drive.google.com/file/d/1J9jGS8HJcm78y_AWhzVW3veYnFhIL5au/view?usp=sharing",
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211865/jayflix%20vid%20posters/photo_2022-09-02_18-45-55_numjln.jpg",
    title: "GENERAL’S WIFE ",
    pref: "Recommended",
    category: "Action",
    description:
      "When a General’s wife is caught having an affair with the General’s aid, the domestic staff resolts to blackmail her to get what they want. How will she get out from this predicament?",
    cast: " Segun Arinze, Bimbo Ademoye, Bolaji Ogunmola",
    director: "Simon Chibuzo Oyimba",
    download: "",
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211865/jayflix%20vid%20posters/photo_2022-09-02_18-45-39_gsw5tv.jpg",
    title: "GLAMOUR GIRLS",
    pref: "Recommended",
    category: "Action",
    description:
      "The world of high-end escorts promises glamour, wealth and the chance of reinvention for a group of women — till a killing and theft threaten it all.",
    cast: "Nse Ikpe-Etim, Sharon Ooja, Toke Makinwa, Segilola Ogidan, Joselyn Dumas, Taymesan Emmanuel.",
    director: "",
    download: "",
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211865/jayflix%20vid%20posters/photo_2022-09-02_18-45-26_mx8mbe.jpg",
    title: "DON’T LEAVE ME ",
    pref: "Recommended",
    category: "Action",
    description:
      "Afam’s will have to place his marriage on hold, as duty calls for an immediate mission.",
    cast: "Larry Koldsweat, Ofia-Afuluagu Mbaka, Frances Nsonwu Ikoroha, Chinenye Ubah, Sambasa Nzeribe",
    director: "",
    download: "",
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211857/jayflix%20vid%20posters/photo_2022-09-02_18-44-17_toanst.jpg",
    title: "GREY ROSES ",
    pref: "Recommended",
    category: "Action",
    description:
      "Afraid of heartbreak, Winifred rejects all advances but a relentless Bernard decides to improvise in a bid to break through her defences.",
    cast: "Wendy Lawal, Mena Sodje, Patrick Dante Oke, Michael Onome Ejoor, Emem Ekpenyong Oniru, Tommy Oyewole",
    director: "",
    download: "",
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211856/jayflix%20vid%20posters/photo_2022-09-02_18-43-31_fq9sdf.jpg",
    title: "EMEM",
    pref: "Recommended",
    category: "Action",
    description:
      "Emem’s marriage to Odera is strongly opposed by a relative who has a firm grip over him.",
    cast: "Michael Godson, Blessing Onwukwe, Ebenezer Eno, Amaka Chukwujekwu, Chichi Eze, Abiola Atoyebi",
    director: "",
    download: "",
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211856/jayflix%20vid%20posters/photo_2022-09-02_18-43-21_hx0vs6.jpg",
    title: "IMPOSTER ",
    pref: "Recommended",
    category: "Action",
    description:
      "Betrayal and retribution are all packed in this action thriller; Find out what happens when four (4) friends gets abducted on new year’s day. Who is the Judas among them?",
    cast: "Desmond Elliot, Ben Touitou, Fred Amata Director: Austin",
    director: "",
    download: "",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211856/jayflix%20vid%20posters/photo_2022-09-02_18-43-10_weljwb.jpg",
    title: "OMOTOKE ",
    pref: "Recommended",
    category: "Action",
    description:
      "After being discriminated against, Omtoke’s meeting with doctor Dafe will be life changing.",
    cast: "After being discriminated against, Omtoke’s meeting with doctor Dafe will be life changing.",
    director: "",
    download: "",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211855/jayflix%20vid%20posters/photo_2022-09-02_18-42-58_n8vecg.jpg",
    title: "CELEBRITY GIRLFRIEND",
    pref: "Recommended",
    category: "Action",
    description:
      "Life takes a dramatic twist for a talented fashion designer when her friend introduces her work to a celebrity.",
    cast: "Okey Uzoeshi, Efe Irele, Emem Ufot, Imoh Eboh, Pelumi Shittu, Ene Okere, Hannah Olayinka, Morola Bamgbala, Michael Adeshina, Kehinde Okunola",
    director: "",
    download: "",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211849/jayflix%20vid%20posters/photo_2022-09-02_18-42-46_ybzumr.jpg",
    title: " LIPSTICK & LIES",
    pref: "Recommended",
    category: "Action",
    description:
      "Using a dating site as bait, Eno catches a redfish and lands herself in trouble",
    cast: "Bimbo Akintola, Emem D. Ufot, Bolaji Ogunmola, Abayomi Alvin, Daniel Etim Effiong, Seleye Fubara",
    director: "",
    download: "",
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211847/jayflix%20vid%20posters/photo_2022-09-02_18-41-21_qsmoo3.jpg",
    title: "ALL THINGS FAIR ",
    pref: "Recommended",
    category: "Action",
    description:
      "A young man is quick to dismiss his marriage after being pressured by his friends. He realizes he might also lose a jewel on the brink of losing everything.",
    cast: "Uzor Arukwe, Genny Uzoma, Eberechukwu Nwizu, Frankincense Eche-Ben, Greg Ojefua, Odera Olivia Orji, Tessy Brown, Sandra Ifudu, Ariella Williams, Sir Chris Akwarandu",
    director: "",
    download: "",
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211847/jayflix%20vid%20posters/photo_2022-09-02_18-40-24_jv0eto.jpg",
    title: "BROWN SKIN GIRL ",
    pref: "Recommended",
    category: "Action",
    description:
      "A struggling scriptwriter finds a job as a maid to an artist who despises ladies with dark-skin.",
    cast: " Ik Ogbonna, Sophie Alakija, Jessie Ekamma Etim-Inyang, Kelvin Brouillette, Caroline Nwokonko",
    director: "",
    download: "",
  },
  {
    id: 22,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211847/jayflix%20vid%20posters/photo_2022-09-02_18-42-20_y4fvdd.jpg",
    title: "LOVE LANGUAGE ",
    pref: "Recommended",
    category: "Action",
    description:
      "The little things that count almost cost Bankole the love of his life.",
    cast: "Uzor Arukwe, Kachi Nnochiri, Scarlet Gomez, Jennifer Frank-Nosa, Diamond Isitua, Ejike Silas Nwogu, Gloria Mirabel Tega",
    director: "",
    download: "",
  },
  {
    id: 23,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211846/jayflix%20vid%20posters/photo_2022-09-02_18-42-09_us1jtn.jpg",
    title: "LOVING AMANDA ",
    pref: "Recommended",
    category: "Action",
    description:
      "Loving Amanda is a romantic story about a young woman’s journey from brokenness to love, healing and redemption.",
    cast: "",
    director: "",
    download: "",
  },
  {
    id: 24,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211846/jayflix%20vid%20posters/photo_2022-09-02_18-40-51_idsn23.jpg",
    title: " GONE",
    pref: "Recommended",
    category: "Action",
    description:
      "Ani leaves his wife, 2 year old daughter and an unborn son back in Nigeria in search for a better life in New York City as a boxer. In a bid to obtain a Green Card, he gets entangled with the mob in New York, arrested, and imprisoned. While he serves prison time in America, his family back home think he is dead. Ani returns to Nigeria after 25 years to reclaim his family only to discover that a whole lot truly can happen in 25 years but he is determined to get his family back, even as his wife has found love, solace and comfort in the arms of another man.",
    cast: "Gabriel Afolayan, Sam Dede, Sophie Alakija, Stella Damacus, Bimbo Ademoye, Gbenga Titiloye, Bimbo Manuel",
    director: "",
    download: "",
  },
  {
    id: 25,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211845/jayflix%20vid%20posters/photo_2022-09-02_18-40-11_u8gi0i.jpg",
    title: "CITY OF DREAMS ",
    pref: "Recommended",
    category: "Action",
    description:
      "A comedic look at Lagos and its residents inherent dreams and aspirations.",
    cast: "Toyin Abraham, Kehinde Bankole, Jide Kosoko, Bolanle Ninolowo, Tina Mba, Charles InogieDirectors: Olumide Fadeyibi",
    director: "",
    download: "",
  },
  {
    id: 26,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211845/jayflix%20vid%20posters/photo_2022-09-02_18-40-11_u8gi0i.jpg",
    title: "CITY OF DREAMS ",
    pref: "Recommended",
    category: "Action",
    description:
      "A comedic look at Lagos and its residents inherent dreams and aspirations.",
    cast: "Toyin Abraham, Kehinde Bankole, Jide Kosoko, Bolanle Ninolowo, Tina Mba, Charles InogieDirectors: Olumide Fadeyibi",
    director: "",
    download: "",
  },
  {
    id: 27,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211843/jayflix%20vid%20posters/photo_2022-09-02_18-39-56_qxj8fs.jpg",
    title: "PROGRESSIVE TAILORS CLUB",
    pref: "Recommended",
    category: "Action",
    description:
      "The Progressive Tailors Club gathers for a meeting to elect a new leader. However, when a trusted executive is eliminated for corruption, it comes down to a choice between the old, the new and the ridiculous.",
    cast: "Beverly Osu, Uzor Arukwe, Funnybone, Blessing Jessica Obasi, Rachel Oniga, Lizzy Jay, Adedimeji Lateef, Bolaji Ogunmola, Femi Adebayo, Kolawole Ajeyemi",
    director: "",
    download: "",
  },
  {
    id: 28,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211841/jayflix%20vid%20posters/photo_2022-09-02_18-39-34_e1upax.jpg",
    title: " COOKED UP LOVE",
    pref: "Recommended",
    category: "Action",
    description:
      "A combination of good looks, charisma and finesse makes Chef Abbey’s TV Show the toast of the cooking community. A twist on the show results in an unlikely reunion with his ex.",
    cast: " Desmond Elliot, Enado Odigie, Bimbo Ademoye, Jimmy Odukoya, Fehintola Olulana.",
    director: "",
    download: "",
  },
  {
    id: 29,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211836/jayflix%20vid%20posters/photo_2022-09-02_18-38-41_youj06.jpg",
    title: " RUNSEWA",
    pref: "Recommended",
    category: "Action",
    description:
      "A combination of good looks, charisma and finesse makes Chef Abbey’s TV Show the toast of the cooking community. A twist on the show results in an unlikely reunion with his ex.",
    cast: " Desmond Elliot, Enado Odigie, Bimbo Ademoye, Jimmy Odukoya, Fehintola Olulana.",
    director: "",
    download: "",
  },
  {
    id: 30,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211836/jayflix%20vid%20posters/photo_2022-09-02_18-38-24_wdq2fn.jpg",
    title: "HOUSE 69",
    pref: "Recommended",
    category: "Romantic",
    description:
      "A young man receives a parcel wrongly addressed to his apartment. This triggers a series of life threatening events for him and his friends",
    cast: "Jide Kosoko, Adeyemi Okanlawon, Joshua Richard, Ebinabo Johnson Potts, Emem Ufot ,Christy Okonkwo ,Blessing Onukwube, Samuel Excel, Ini Efanga .",
    director: "",
    download: "",
  },
  {
    id: 31,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211835/jayflix%20vid%20posters/photo_2022-09-02_18-36-31_ttllmd.jpg",
    title: "DEAR DIARY",
    pref: "Recommended",
    category: "Romantic",
    description:
      "Zara and her husband must defend their marriage from the claws of Scandalous Sam. He reaches a deadlock at the brink of achieving his selfish gains.",
    cast: "Nancy Isime, Deyemi Okanlawon, Kalu Ikeagwu, Priscilla Okpara, Dan Ugoji, Chidi Nwachukwu, Mbaninuju Patricia  Director: Richards Omos Iboyi",
    director: "",
    download: "",
  },
  {
    id: 32,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211831/jayflix%20vid%20posters/photo_2022-09-02_18-36-01_errfsu.jpg",
    title: " BREADED LIFE ",
    pref: "Recommended",
    category: "Romantic",
    description:
      "An irresponsible young man in conflict with his mother wakes up one day and to his surprise, no-one he knows can recognize him, except for a local bread hawker….",
    cast: "Tina Mba, Amuda Eko, Funny Bone, Jide Kosoko, Lizzy Jay, Nkechi Blessing Sunday, Tomiwa Sage, Karen Spikes, MC Lively, Bisola Aiyeola, Timini Egbuson, Bimbo Ademoye, Bolanle Ninalowo, Adedimeji Lateef",
    director: "",
    download: "",
  },
  {
    id: 33,
    img: "https://res.cloudinary.com/isreal/image/upload/v1662211831/jayflix%20vid%20posters/photo_2022-09-02_18-35-29_ndn9eb.jpg",
    title: " INTRODUCING THE KUJUS",
    pref: "Recommended",
    category: "Romantic",
    description:
      "Introducing The Kujus tells the story of siblings who have been at crossroads since their mother’s death.",
    cast: "Bisola Aiyeola, Timini Egbuson, Femi Jacobs, Kunle Remi, Ronke Odusanya, Bimbo Ademoye, MC Lively, Sophie Alakija, Folaremi Agunbiade, Mimi Onalaja, Chris Iheuwa, Temitope Ogunleye, Ayomide Ogunleye",
    director: "",
    download: "",
  },
];
export default recommendedDB;
